// Package db manages the SQLite database: schema, connection, and pragmas.
package db

import (
	"database/sql"
	"os"
	"path/filepath"
	"strconv"

	_ "modernc.org/sqlite" // register sqlite3 driver
)

// schemaVersion is the current cache schema version. The SQLite DB is a derived
// cache of the source files, not a source of truth: bumping this version and
// rebuilding the cache (via CreateSchema + a follow-up scan) replaces
// column-by-column ALTER migrations.
const schemaVersion = 1

const schemaSQL = `
CREATE TABLE IF NOT EXISTS repos (
  id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL, path TEXT UNIQUE NOT NULL,
  graph_path TEXT, graph_mtime INTEGER, graph_node_count INTEGER, graph_last_seen INTEGER,
  code_graph_path TEXT, code_graph_mtime INTEGER, code_graph_node_count INTEGER
);

CREATE TABLE IF NOT EXISTS external_graphs (
  name TEXT PRIMARY KEY, graph_path TEXT NOT NULL, graph_mtime INTEGER,
  node_count INTEGER, added_at INTEGER, kind TEXT NOT NULL DEFAULT 'graphify'
);

CREATE TABLE IF NOT EXISTS specs (
  id            INTEGER PRIMARY KEY,
  repo          TEXT NOT NULL,
  path          TEXT NOT NULL,
  project       TEXT NOT NULL,
  name          TEXT NOT NULL,
  title         TEXT NOT NULL,
  tags          TEXT DEFAULT '',
  summary       TEXT DEFAULT '',
  fullpath      TEXT NOT NULL,
  modified      TEXT NOT NULL,
  modified_unix INTEGER NOT NULL DEFAULT 0,
  size          INTEGER NOT NULL,
  ext           TEXT NOT NULL,
  content       TEXT DEFAULT '',
  UNIQUE(repo, path)
);

CREATE VIRTUAL TABLE IF NOT EXISTS specs_fts USING fts5(
  repo, name, title, tags, summary, content,
  content='', tokenize='porter unicode61'
);

CREATE TABLE IF NOT EXISTS spec_tags (
  spec_id INTEGER NOT NULL,
  tag     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS spec_vectors (
  spec_id INTEGER PRIMARY KEY,
  repo    TEXT NOT NULL,
  dim     INTEGER NOT NULL,
  vec     BLOB    NOT NULL
);

CREATE TABLE IF NOT EXISTS spec_edges (
  src_spec_id INTEGER NOT NULL,
  dst_spec_id INTEGER NOT NULL,
  weight      REAL    NOT NULL,
  PRIMARY KEY (src_spec_id, dst_spec_id)
);

CREATE TABLE IF NOT EXISTS meta ( key TEXT PRIMARY KEY, value TEXT );

CREATE INDEX IF NOT EXISTS idx_specs_name_lower  ON specs(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_specs_project     ON specs(project);
CREATE INDEX IF NOT EXISTS idx_specs_modified    ON specs(modified_unix DESC);
CREATE INDEX IF NOT EXISTS idx_tags              ON spec_tags(tag);
CREATE INDEX IF NOT EXISTS idx_tags_lower        ON spec_tags(LOWER(tag));
CREATE INDEX IF NOT EXISTS idx_spec_tags_spec_id ON spec_tags(spec_id);
CREATE INDEX IF NOT EXISTS idx_spec_vectors_repo ON spec_vectors(repo);
CREATE INDEX IF NOT EXISTS idx_spec_edges_src    ON spec_edges(src_spec_id);
`

// derivedTables are the cache tables regenerated by a filesystem rescan. They
// are dropped and recreated when the schema version changes (or when a legacy
// pre-versioned cache is detected), rather than migrated column-by-column.
var derivedTables = []string{
	"specs", "specs_fts", "spec_tags", "spec_vectors", "spec_edges",
	"repos", "external_graphs",
}

// Open opens (or creates) the SQLite database at dbPath with performance pragmas set.
func Open(dbPath string) (*sql.DB, error) {
	if err := os.MkdirAll(filepath.Dir(dbPath), 0755); err != nil {
		return nil, err
	}

	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return nil, err
	}

	// Single writer connection — keeps WAL locking simple
	db.SetMaxOpenConns(1)

	for _, pragma := range []string{
		// busy_timeout makes a connection wait (up to the bound) for a lock to
		// clear instead of failing immediately with SQLITE_BUSY. Combined with WAL
		// below, this lets a concurrent scan (writer) and query (reader) contend
		// on the same DB without the read failing or the index corrupting (R-2.7).
		"PRAGMA busy_timeout=5000",
		"PRAGMA journal_mode=WAL",
		"PRAGMA synchronous=NORMAL",
		"PRAGMA cache_size=-32000", // 32 MB page cache
		// temp_store intentionally left as default (FILE) so SQLite can spill
		// large sort/index scratch work to disk rather than holding it in RAM.
		// Foreign keys intentionally omitted: consistency is guaranteed by the
		// atomic rebuild of the derived cache, so FKs would only cost insert
		// overhead.
	} {
		if _, err := db.Exec(pragma); err != nil {
			db.Close()
			return nil, err
		}
	}

	// mmap is an optional performance boost. If the platform/driver rejects it,
	// degrade gracefully rather than failing Open.
	_, _ = db.Exec("PRAGMA mmap_size=268435456")

	return db, nil
}

// CreateSchema ensures the derived cache has the current schema shape, using a
// PRAGMA user_version guard instead of additive ALTER migrations. Because the
// DB is a derived cache of the source files (not a source of truth), a schema
// change bumps schemaVersion and rebuilds the cache: stale-shaped derived
// tables are dropped and recreated, and a follow-up scan repopulates them.
func CreateSchema(db *sql.DB) error {
	var version int
	if err := db.QueryRow("PRAGMA user_version").Scan(&version); err != nil {
		return err
	}

	switch {
	case version == 0:
		// Fresh DB, or a legacy cache from before versioning (both report 0).
		// Distinguish them: a legacy cache has a specs table without the new
		// modified_unix column. Drop the derived tables so the stale shape is
		// rebuilt cleanly; a follow-up scan repopulates.
		hasModifiedUnix, err := columnExists(db, "specs", "modified_unix")
		if err != nil {
			return err
		}
		specsExists, err := tableExists(db, "specs")
		if err != nil {
			return err
		}
		if specsExists && !hasModifiedUnix {
			if err := dropDerivedTables(db); err != nil {
				return err
			}
		}
	case version < schemaVersion:
		// Stale cache from an older schema version — rebuild.
		if err := dropDerivedTables(db); err != nil {
			return err
		}
	}
	// version == schemaVersion falls through: all DDL is CREATE ... IF NOT
	// EXISTS, so re-running is a safe no-op.

	if _, err := db.Exec(schemaSQL); err != nil {
		return err
	}
	if _, err := db.Exec("PRAGMA user_version = " + strconv.Itoa(schemaVersion)); err != nil {
		return err
	}
	return nil
}

// dropDerivedTables drops every derived cache table so the fresh DDL can
// recreate them with the current shape.
func dropDerivedTables(db *sql.DB) error {
	for _, t := range derivedTables {
		if _, err := db.Exec("DROP TABLE IF EXISTS " + t); err != nil {
			return err
		}
	}
	return nil
}

// tableExists reports whether a table with the given name exists.
func tableExists(db *sql.DB, table string) (bool, error) {
	var n int
	err := db.QueryRow(
		"SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", table,
	).Scan(&n)
	if err != nil {
		return false, err
	}
	return n > 0, nil
}

// columnExists reports whether the given column exists on the given table.
// Returns (false, nil) when the table itself does not exist.
func columnExists(db *sql.DB, table, column string) (bool, error) {
	rows, err := db.Query("PRAGMA table_info(" + table + ")")
	if err != nil {
		return false, err
	}
	defer rows.Close()
	for rows.Next() {
		var (
			cid       int
			name      string
			ctype     string
			notnull   int
			dfltValue sql.NullString
			pk        int
		)
		if err := rows.Scan(&cid, &name, &ctype, &notnull, &dfltValue, &pk); err != nil {
			return false, err
		}
		if name == column {
			return true, nil
		}
	}
	return false, rows.Err()
}

// GetMeta retrieves a value from the meta table. Returns "" if the key is absent.
func GetMeta(db *sql.DB, key string) string {
	var val string
	db.QueryRow("SELECT value FROM meta WHERE key=?", key).Scan(&val) //nolint:errcheck
	return val
}

// SetMeta stores a key/value pair in the meta table.
func SetMeta(db *sql.DB, key, value string) error {
	_, err := db.Exec("INSERT OR REPLACE INTO meta (key,value) VALUES (?,?)", key, value)
	return err
}
